import type { ContentAnalysis, ExportMeta } from "./types";
import { buildMarkdownExport, buildTxtExport, downloadBlob, formatTashkentNow, safeFilename } from "./helpers";

export async function exportMarkdown(meta: ExportMeta): Promise<void> {
  const md = buildMarkdownExport(meta);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  downloadBlob(blob, `${safeFilename(meta.title)}.md`);
}

export async function exportTxt(meta: ExportMeta): Promise<void> {
  const txt = buildTxtExport(meta);
  const blob = new Blob([txt], { type: "text/plain;charset=utf-8" });
  downloadBlob(blob, `${safeFilename(meta.title)}.txt`);
}

export async function exportPdf(meta: ExportMeta, analysis: ContentAnalysis): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  let y = margin;

  const addPageFooter = (pageNum: number) => {
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text("Generated by AI Executive Platform", margin, 287);
    doc.text(String(pageNum), pageW - margin, 287, { align: "right" });
    doc.setTextColor(0);
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("AI Executive Platform", margin, y);
  y += 10;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Agent: ${meta.agentLabel}`, margin, y);
  y += 6;
  doc.text(`Hisobot: ${meta.title}`, margin, y);
  y += 6;
  doc.text(`Sana: ${formatTashkentNow()} (Asia/Tashkent)`, margin, y);
  y += 6;
  if (analysis.freshnessLine) {
    doc.text(`Freshness: ${analysis.freshnessLine}`, margin, y);
    y += 6;
  }
  y += 4;
  doc.setDrawColor(200);
  doc.line(margin, y, pageW - margin, y);
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Executive Summary", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const summaryLines = doc.splitTextToSize(analysis.executiveSummary, pageW - margin * 2);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("To'liq javob", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const body = meta.content.replace(/\*\*/g, "").replace(/#{1,6}\s/g, "");
  const lines = doc.splitTextToSize(body, pageW - margin * 2);
  let pageNum = 1;

  for (const line of lines) {
    if (y > 270) {
      addPageFooter(pageNum);
      doc.addPage();
      pageNum++;
      y = margin;
    }
    doc.text(line, margin, y);
    y += 5;
  }
  addPageFooter(pageNum);
  doc.save(`${safeFilename(meta.title)}.pdf`);
}

export async function exportDocx(meta: ExportMeta, analysis: ContentAnalysis): Promise<void> {
  const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    HeadingLevel,
    Table,
    TableRow,
    TableCell,
    WidthType,
    BorderStyle,
  } = await import("docx");

  type DocChild = InstanceType<typeof Paragraph> | InstanceType<typeof Table>;
  const children: DocChild[] = [
    new Paragraph({ text: "AI Executive Platform", heading: HeadingLevel.TITLE }),
    new Paragraph({ children: [new TextRun({ text: `Agent: ${meta.agentLabel}`, bold: true })] }),
    new Paragraph(`Hisobot: ${meta.title}`),
    new Paragraph(`Sana: ${formatTashkentNow()} (Asia/Tashkent)`),
  ];
  if (analysis.freshnessLine) {
    children.push(new Paragraph(`Bitrix24: ${analysis.freshnessLine}`));
  }
  children.push(
    new Paragraph({ text: "Executive Summary", heading: HeadingLevel.HEADING_1 }),
    new Paragraph(analysis.executiveSummary),
    new Paragraph({ text: "To'liq javob", heading: HeadingLevel.HEADING_1 })
  );

  for (const section of analysis.sections) {
    children.push(
      new Paragraph({ text: section.name, heading: HeadingLevel.HEADING_2 }),
      new Paragraph(section.body.replace(/\*\*/g, ""))
    );
  }

  for (const table of analysis.tables) {
    children.push(new Paragraph({ text: table.name, heading: HeadingLevel.HEADING_2 }));
    const rows = [
      new TableRow({
        children: table.headers.map(
          (h) =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: h, bold: true })] })],
              width: { size: 100 / table.headers.length, type: WidthType.PERCENTAGE },
            })
        ),
      }),
      ...table.rows.map(
        (row) =>
          new TableRow({
            children: row.map((cell) => new TableCell({ children: [new Paragraph(cell)] })),
          })
      ),
    ];
    children.push(
      new Table({
        rows,
        width: { size: 100, type: WidthType.PERCENTAGE },
        borders: {
          top: { style: BorderStyle.SINGLE, size: 1 },
          bottom: { style: BorderStyle.SINGLE, size: 1 },
          left: { style: BorderStyle.SINGLE, size: 1 },
          right: { style: BorderStyle.SINGLE, size: 1 },
        },
      })
    );
  }

  children.push(
    new Paragraph(""),
    new Paragraph({
      children: [new TextRun({ text: "Generated by AI Executive Platform", italics: true, size: 18 })],
    })
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, `${safeFilename(meta.title)}.docx`);
}

export async function exportXlsx(meta: ExportMeta, analysis: ContentAnalysis): Promise<void> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();

  const summaryData = [
    ["AI Executive Platform"],
    ["Agent", meta.agentLabel],
    ["Hisobot", meta.title],
    ["Sana", formatTashkentNow()],
    ["Timezone", "Asia/Tashkent"],
    ["Freshness", analysis.freshnessLine || ""],
    [],
    ["Executive Summary"],
    [analysis.executiveSummary],
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summaryData), "Summary");

  if (analysis.tables.length) {
    for (const table of analysis.tables.slice(0, 7)) {
      const sheetName = table.name.slice(0, 31);
      const data = [table.headers, ...table.rows];
      XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(data), sheetName);
    }
  } else {
    const kpiData = [["Metric", "Value"], ["Content length", String(meta.content.length)]];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(kpiData), "KPIs");
  }

  const recLines = meta.content.split("\n").filter((l) => /^[-*]\s/.test(l.trim()));
  if (recLines.length) {
    XLSX.utils.book_append_sheet(
      wb,
      XLSX.utils.aoa_to_sheet([["Recommendations"], ...recLines.map((l) => [l.replace(/^[-*]\s/, "")])]),
      "Recommendations"
    );
  }

  const out = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  downloadBlob(
    new Blob([out], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `${safeFilename(meta.title)}.xlsx`
  );
}
