import type { ExportMeta } from "./types";

export function formatTashkentNow(): string {
  return new Intl.DateTimeFormat("uz-UZ", {
    timeZone: "Asia/Tashkent",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(new Date());
}

export function buildMarkdownExport(meta: ExportMeta): string {
  const lines = [
    `# AI Executive Platform`,
    ``,
    `**Agent:** ${meta.agentLabel}`,
    `**Hisobot:** ${meta.title}`,
    `**Sana:** ${formatTashkentNow()} (Asia/Tashkent)`,
  ];
  if (meta.fetchedAt || meta.content.includes("Bitrix24")) {
    lines.push(`**Bitrix24 Freshness:** ${meta.fetchedAt || "included in content"}`);
  }
  if (meta.userQuestion) {
    lines.push(``, `## Savol`, meta.userQuestion);
  }
  lines.push(``, `## Javob`, meta.content, ``, `---`, `*Generated by AI Executive Platform*`);
  return lines.join("\n");
}

export function buildTxtExport(meta: ExportMeta): string {
  return [
    "AI Executive Platform",
    `Agent: ${meta.agentLabel}`,
    `Sana: ${formatTashkentNow()} (Asia/Tashkent)`,
    meta.userQuestion ? `\nSavol:\n${meta.userQuestion}` : "",
    `\n${meta.content}`,
    "\n---\nGenerated by AI Executive Platform",
  ]
    .filter(Boolean)
    .join("\n");
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function safeFilename(base: string): string {
  return base.replace(/[^\w\-]+/g, "_").slice(0, 60);
}
